name: paqr3
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - pandas>=1.5.0
  - numpy>=1.20.0
  - scipy>=1.7.0
  - intervaltree
  - gtfparse
  - HTSeq
  - pybedtools
  - deeptools
  - ucsc-gtftogenepred
  - ucsc-bedgraphtobigwig
  - pigz
  - pip >=20.2.3
  - pip:
    - -e .